apiVersion: apps/v1
kind: Deployment

metadata:
  name: readmission-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: readmission-api

  template:
    metadata:
      labels:
        app: readmission-api

    spec:
      imagePullSecrets:
      - name: acr-secret

    containers:
      - name: readmission-api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client-id
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: tenant-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client-secret